name: Publish package to GitHub Packages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      # Use Node.js with pnpm caching
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: "https://npm.pkg.github.com"
          node-version: "20" # replace with your desired Node.js version
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
